#!/bin/bash

declare -a errors

function validate_jq() {
  local json="$1"
  local query="$2"
  local expected="$3"

  local actual
  actual=$(echo "$json" | jq -r "$query")

  if ! echo "$actual" | grep -q "$expected"; then
    errors+=("$query is set incorrectly:
    expected: $expected
    but was:  $actual
")
  fi
}

function check_errors() {
  num_errors="${#errors[@]}"
  if [ "$num_errors" -ne 0 ]; then
    printf "%s\n" "${errors[@]}"
    exit 1
  else
    echo "all good!"
  fi
}

repo=$(gh api 'repos/{owner}/{repo}')

validate_jq "$repo" '.allow_squash_merge' 'true'
validate_jq "$repo" '.allow_merge_commit' 'false'
validate_jq "$repo" '.allow_rebase_merge' 'false'

check_errors
