name: Rust Setup
description: Rust Setup
runs:
  using: composite
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy, llvm-tools-preview

    # needed dirs: https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
    - name: Cache Cargo System (cargo install)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
        key: cargo-system-${{ runner.os }}-${{ hashFiles('~/.cargo/.crates.toml', '~/.cargo/.crates2.json') }}

    # example: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Cache Cargo Repo (cargo install)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-repo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
