name: Rust Setup
description: Rust Setup
runs:
  using: composite
  steps:
    # Setup
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    # Cache
    # example: https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    # needed dirs: https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
    - name: Cache cargo bin
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
