[package]
name = "kindle-to-anki"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-async-std-rustls", "sqlite" ] }
async-std = { version = "1", features = [ "attributes" ] }
futures = "0.3.28"
csv = "1.2.2"
tempfile = "3.5.0"
itertools = "0.11.0"
