name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: ./.github/actions/setup

      - name: Install more cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest

      # test
      - name: Run tests and generate coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest --profile ci

      - uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: test
          report_paths: "**/junit.xml"

      # lint
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
          name: lint
        if: always()

      # coverage
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        if: always()
