name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ./.github/actions/setup
      - name: Install more cargo tools
        run: echo yes | cargo binstall cargo-llvm-cov cargo-nextest
      - name: Run tests and generate coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest --profile ci
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: test
          report_paths: "**/junit.xml"
      - uses: n-ryu/test-reporter@v0.0.2
        if: always()
        with:
          name: n-ryu test report
          path: "**/junit.xml"
          reporter: java-junit
      - uses: test-summary/action@v2
        with:
          paths: "**/junit.xml"
        if: always()
      - uses: turing85/publish-report@v1
        with:
          recreate-comment: true
        if: always()
      - uses: turing85/publish-report@v1
        with:
          report-name: turing85 test
          report-path: "**/junit.xml"
          comment-message-success: |
            ### {0} Report
            ---
            Tests succeeded 🎉

            | Passed | Failed | Skipped |
            |--------|--------|---------|
            | ✅ {1} | ❌ {2} | ⚠️ {3}   |

            You can see the report [here]({4}).
          comment-message-failure: |
            ### {0} Report
            ---
            Tests failed 🔥

            | Passed | Failed | Skipped |
            |--------|--------|---------|
            | ✅ {1} | ❌ {2} | ⚠️ {3}   |

            You can see the report [here]({4}).
        if: always()
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
          name: lint
        if: always()
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
        if: always()
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          fail_ci_if_error: true
