name: CI
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  actions: write # Necessary to cancel workflow executions
  checks: write # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ./.github/actions/setup
      - name: Install more cargo tools
        run: echo yes | cargo binstall cargo-llvm-cov cargo-nextest
      - name: Run tests and generate coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest --profile ci
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: mikepenz test report
          report_paths: "**/junit.xml"
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: dorny test report
          path: "**/junit.xml"
          reporter: java-junit
      - uses: test-summary/action@v2
        with:
          paths: "**/junit.xml"
        if: always()
      - uses: turing85/publish-report@v1
        with:
          report-path: "**/junit.xml"
          recreate-comment: true
        if: always()
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
        if: always()
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          fail_ci_if_error: true
