name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ./.github/actions/setup
      - name: Install Tarpaulin
        run: echo yes | cargo binstall cargo-tarpaulin
      - name: Run tests and generate coverage
        run: cargo tarpaulin --engine llvm --skip-clean --all-features --no-fail-fast --out lcov
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
        env:
          NODE_COVERALLS_DEBUG: 1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
