name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: ./.github/actions/setup
      - name: Install more cargo tools
        run: echo yes | cargo binstall cargo-llvm-cov nextest
      - name: Run tests and generate coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
