name: Lint Repo Settings
on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Lint}
        run: ./.github/gh-lint
